apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sock-shop
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: rabbitmq
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {cpu: 500m, memory: 768Mi}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
        - name: rabbitmq-exporter
          resources:
            requests: {cpu: 25m, memory: 64Mi}
            limits: {cpu: 100m, memory: 128Mi}
      volumes:
        - name: data
          emptyDir: {sizeLimit: 512Mi}
