apiVersion: v1
kind: Secret
metadata:
  name: anomaly-detector-postgres
  namespace: agents
type: Opaque
stringData:
  POSTGRES_DB: "++++++++"
  POSTGRES_USER: "++++++++"
  POSTGRES_PASSWORD: "++++++++"
