{
 "title": "CPU Throttling Dashboard",
 "tags": [
  "kubernetes",
  "cpu",
  "throttling"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Throttling by Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Throttled Seconds",
   "type": "timeseries",
   "description": "CPU throttled time per second, aggregated by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_cfs_throttled_seconds_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n)\nor on (pod)\n0 * sum by (pod) (\n  kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Throttled Periods",
   "type": "timeseries",
   "description": "Percentage of CFS periods throttled, aggregated by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n)\n/\nsum by (pod) (\n  rate(container_cpu_cfs_periods_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Throttling by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node CPU Throttled Periods",
   "type": "timeseries",
   "description": "Percentage of CFS periods throttled for pods running on each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (node) (\n  rate(container_cpu_cfs_throttled_periods_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n  * on (namespace, pod) group_left(node)\n  max by (namespace, pod, node) (\n    kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}\n  )\n)\n/\nsum by (node) (\n  rate(container_cpu_cfs_periods_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n  * on (namespace, pod) group_left(node)\n  max by (namespace, pod, node) (\n    kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node CPU Throttled Seconds",
   "type": "timeseries",
   "description": "CPU throttled time per second for pods running on each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  rate(container_cpu_cfs_throttled_seconds_total{\n    namespace=~\"$namespace\",\n    pod=~\"$pod\",\n    container!=\"\",\n    container!=\"POD\",\n    image!=\"\"\n  }[$__rate_interval])\n  * on (namespace, pod) group_left(node)\n  max by (namespace, pod, node) (\n    kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}