apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: node-cpu-worker-3-single
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: PhysicalMachineChaos
  physicalmachineChaos:
    action: stress-cpu
    mode: one
    selector:
      physicalMachines:
        chaos-mesh:
        - worker-node-3
    stress-cpu:
      workers: 4
      load: 95
    duration: 29s
