apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: node-delay-worker-5
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: PhysicalMachineChaos
  physicalmachineChaos:
    action: network-delay
    mode: one
    selector:
      physicalMachines:
        chaos-mesh:
        - worker-node-5
    network-delay:
      device: eth0
      latency: 250ms
      jitter: 50ms
      correlation: '25'
    duration: 25s
