apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: single-recommendationservice-cpu
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: StressChaos
  stressChaos:
    mode: all
    selector:
      namespaces:
      - online-boutique
      podPhaseSelectors:
      - Running
      expressionSelectors:
      - key: app
        operator: In
        values:
        - recommendationservice
    stressors:
      cpu:
        workers: 1
        # 45% of one CPU approximates the 500m limit minus 50m.
        load: 45
    duration: 25s
