{
 "title": "Online Boutique Resource Utilization",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Response Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (destination_workload, le) (\n    rate(istio_request_duration_milliseconds_bucket{\n      reporter=\"destination\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization (CPU request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"online-boutique\", container!=\"\"}[1m])) by (pod)\n/\nsum(kube_pod_container_resource_requests{namespace=\"online-boutique\", resource=\"cpu\"}) by (pod)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (destination_workload, le) (\n    rate(istio_request_duration_milliseconds_bucket{\n      reporter=\"destination\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (destination_workload) (\n  rate(istio_requests_total{reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}