[control_plane]
master-node ansible_host=192.0.2.1

[tool_nodes]
tools-node ansible_host=192.0.2.2

[service_nodes]
worker-node-1 ansible_host=192.0.2.3 physical_machine_address=https://192.0.2.3:31768
worker-node-2 ansible_host=192.0.2.4 physical_machine_address=https://192.0.2.4:31768
worker-node-3 ansible_host=192.0.2.5 physical_machine_address=https://192.0.2.5:31768
worker-node-4 ansible_host=192.0.2.6 physical_machine_address=https://192.0.2.6:31768
worker-node-5 ansible_host=192.0.2.7 physical_machine_address=https://192.0.2.7:31768
worker-node-6 ansible_host=192.0.2.8 physical_machine_address=https://192.0.2.8:31768

[cluster_nodes:children]
control_plane
tool_nodes
service_nodes

[all:vars]
ansible_user=ubuntu

