apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: node-cpu-worker-2
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: PhysicalMachineChaos
  physicalmachineChaos:
    action: stress-cpu
    mode: one
    selector:
      physicalMachines:
        chaos-mesh:
        - worker-node-2
    stress-cpu:
      workers: 8
      load: 90
    duration: 25s
