apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: sock-shop-shipping-bandwidth
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: NetworkChaos
  networkChaos:
    action: bandwidth
    mode: all
    selector:
      namespaces:
      - sock-shop
      podPhaseSelectors:
      - Running
      expressionSelectors:
      - key: app
        operator: In
        values:
        - shipping
    bandwidth:
      rate: 1mbps
      limit: 2097152
      buffer: 10000
    duration: 25s
