apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: sock-shop-carts-cpu
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: StressChaos
  stressChaos:
    mode: all
    selector:
      namespaces:
      - sock-shop
      podPhaseSelectors:
      - Running
      expressionSelectors:
      - key: app
        operator: In
        values:
        - carts
    stressors:
      cpu:
        workers: 1
        load: 25
    duration: 25s
