apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: sock-shop-shipping-memory
  namespace: chaos-mesh
spec:
  schedule: '@every 30s'
  historyLimit: 1
  concurrencyPolicy: Forbid
  type: StressChaos
  stressChaos:
    mode: all
    selector:
      namespaces:
      - sock-shop
      podPhaseSelectors:
      - Running
      expressionSelectors:
      - key: app
        operator: In
        values:
        - shipping
    stressors:
      memory:
        workers: 1
        size: 400MB
    duration: 25s
