apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: sock-shop
spec:
  template:
    spec:
      containers:
      - name: user-db
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi
