from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

# fmt: off
class OutputFilter(BaseModel):
    include_paths: list[str] | None = Field(
        default=None,
        description="Optional dot paths to keep, e.g. ['data.data.result'] or ['data.data.result.0']. If omitted, the full response is considered before other limits.",
    )
    exclude_paths: list[str] | None = Field(
        default=None,
        description="Optional dot paths to remove from the response before compaction.",
    )
    keys: list[str] | None = Field(
        default=None,
        description="Optional dictionary keys to preserve recursively, e.g. ['metric', 'value', 'stream', 'values', 'traceID', 'spans'].",
    )
    contains: str | None = Field(
        default=None,
        description="Optional substring used to keep only matching list items after JSON serialization.",
    )
    max_items: int = Field(default=100, description="Maximum list items or object keys to keep at each level.")
    max_depth: int = Field(default=6, description="Maximum nested depth to preserve before summarizing.")
    max_string_length: int = Field(default=2000, description="Maximum string length before truncation.")


class FlexibleKubectlRequest(BaseModel):
    args: str | list[str] = Field(
        description="Arguments after kubectl, as a shell-like string or token list. Examples: 'get pods -n online-boutique -o wide', ['describe', 'svc', 'frontend', '-n', 'online-boutique']."
    )
    grep: str | None = Field(default=None, description="Optional regex/substring used to keep only matching stdout lines. Use this instead of shell pipes.")
    timeout_seconds: int | None = Field(default=None, description="Optional command timeout override.")


class FlexiblePrometheusRequest(BaseModel):
    promql: str = Field(description="PromQL query generated by the agent.")
    query_type: str = Field(default="instant", description="Use 'instant' or 'range'. This is an argument on the prometheus tool, not a separate prometheus.query_range tool.")
    time: str | None = Field(default=None, description="Optional evaluation time for instant queries.")
    start: str | None = Field(default=None, description="Range query start timestamp.")
    end: str | None = Field(default=None, description="Range query end timestamp.")
    step: str | None = Field(default=None, description="Range query step, e.g. 30s, 1m, or 5m.")
    filter: OutputFilter | None = Field(default=None, description="Optional output filter to reduce bloated Prometheus JSON.")


class FlexibleLokiRequest(BaseModel):
    logql: str = Field(description="LogQL query generated by the agent.")
    query_type: str = Field(default="range", description="Use 'range' or 'instant'. This is an argument on the loki tool, not a separate loki.query tool.")
    start: str | None = Field(default=None, description="Optional range start timestamp.")
    end: str | None = Field(default=None, description="Optional range end timestamp.")
    since: str | None = Field(default=None, description="Optional Loki relative duration such as 15m.")
    limit: int = Field(default=100, description="Maximum log entries or streams to request.")
    direction: str = Field(default="BACKWARD", description="Loki query direction: BACKWARD or FORWARD.")
    filter: OutputFilter | None = Field(default=None, description="Optional output filter to reduce bloated Loki JSON.")


class JaegerListServicesRequest(BaseModel):
    pass


class JaegerRetrieveSlowTracesRequest(BaseModel):
    service: str = Field(default="frontend.online-boutique", description="Jaeger service name to sample, e.g. frontend.online-boutique.")
    lookback: str = Field(default="30m", description="Lookback window for action='slow_traces', e.g. 15m, 30m, 1h.")
    limit: int = Field(default=5, description="Number of slow trace summaries to return for action='slow_traces'.")
    min_duration: str | None = Field(default=None, description="Optional Jaeger minDuration for action='slow_traces', e.g. 20ms, 100ms, 1s.")
    max_duration: str | None = Field(default=None, description="Optional Jaeger maxDuration for action='slow_traces', e.g. 1s.")


class JaegerInvestigateTraceRequest(BaseModel):
    trace_id: str = Field(description="Jaeger trace ID to summarize.")


class JaegerRetrieveBottleneckRequest(BaseModel):
    trace_id: str = Field(description="Jaeger trace ID to inspect for the likely slow service/span.")


class NetworkTopologyRequest(BaseModel):
    plane: Literal["overlay", "underlay", "both"] = Field(
        default="both",
        description="Network plane to inspect. Use overlay for Flannel pod networking, underlay for node networking, or both.",
    )


class NetworkLatencyMatrixRequest(BaseModel):
    plane: Literal["overlay", "underlay", "both"] = Field(
        default="both",
        description="Network plane to measure. Use both to compare Flannel overlay and node underlay paths.",
    )
    source_nodes: list[str] | None = Field(
        default=None,
        description="Optional worker node names to probe from. Omit to use all Ready role=services nodes with healthy probes.",
    )
    target_nodes: list[str] | None = Field(
        default=None,
        description="Optional worker node names to probe. Omit to use all Ready role=services nodes with healthy probes.",
    )
    count: int = Field(
        default=5,
        ge=1,
        le=10,
        description="ICMP samples per directed source-target pair.",
    )
    include_self: bool = Field(
        default=False,
        description="Include same-node probe pairs when true.",
    )


class NetworkBandwidthRequest(BaseModel):
    source_node: str = Field(description="Ready role=services worker node to run the iperf3 client from.")
    target_node: str = Field(description="Different Ready role=services worker node hosting the iperf3 server.")
    plane: Literal["overlay", "underlay"] = Field(
        default="overlay",
        description="Use overlay for the Flannel pod path or underlay for the node IP path.",
    )
    protocol: Literal["tcp", "udp"] = Field(default="tcp", description="iperf3 transport protocol.")
    direction: Literal["forward", "reverse", "bidirectional"] = Field(
        default="forward",
        description="Traffic direction relative to source_node and target_node.",
    )
    duration_seconds: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Bounded active test duration.",
    )
    bitrate_mbps: int = Field(
        default=50,
        ge=1,
        le=100,
        description="Hard traffic rate limit in megabits per second for the one-stream test.",
    )


class NetworkPathRequest(BaseModel):
    source_node: str = Field(description="Ready role=services worker node to trace from.")
    target_node: str = Field(description="Ready role=services worker node to trace to.")
    plane: Literal["overlay", "underlay"] = Field(
        default="overlay",
        description="Use overlay for the Flannel pod path or underlay for the node IP path.",
    )
    protocol: Literal["icmp", "tcp"] = Field(
        default="icmp",
        description="Use ICMP tracing or TCP tracing to the probe's port 5201.",
    )
    cycles: int = Field(default=5, ge=1, le=10, description="Bounded mtr report cycles.")


class NetworkDnsRequest(BaseModel):
    source_node: str = Field(description="Ready role=services worker node to issue the DNS query from.")
    query: str = Field(description="Kubernetes service DNS name ending in svc.cluster.local.")
    plane: Literal["overlay", "underlay"] = Field(
        default="overlay",
        description="Probe network namespace to issue the query from.",
    )
    record_type: Literal["A", "AAAA", "SRV"] = Field(default="A", description="DNS record type.")
    timeout_seconds: int = Field(default=2, ge=1, le=5, description="Per-query DNS timeout.")
    retries: int = Field(default=1, ge=1, le=2, description="Bounded DNS query attempts.")


class NetworkTcpConnectRequest(BaseModel):
    source_node: str = Field(description="Ready role=services worker node to connect from.")
    namespace: str = Field(description="Kubernetes namespace containing the destination Service.")
    service: str = Field(description="Kubernetes Service name. Arbitrary hosts and IP addresses are not accepted.")
    port: int = Field(ge=1, le=65535, description="Port declared by the destination Service.")
    plane: Literal["overlay", "underlay"] = Field(
        default="overlay",
        description="Probe network namespace to connect from.",
    )
    attempts: int = Field(default=3, ge=1, le=5, description="Bounded TCP connection attempts.")
    timeout_seconds: int = Field(default=2, ge=1, le=5, description="Timeout for each TCP connection attempt.")


class ClusterProfileBaselineRequest(BaseModel):
    namespace: str = Field(
        default="online-boutique",
        pattern=r"^[a-z0-9](?:[-a-z0-9]*[a-z0-9])?$",
        max_length=63,
        description="Kubernetes namespace whose complete live Deployment inventory will be profiled.",
    )
    window_minutes: int = Field(
        default=30,
        ge=5,
        le=60,
        description="Bounded metric and log window. The window is recent by default or centered on evaluation_time when supplied.",
    )
    evaluation_time: datetime | None = Field(
        default=None,
        description="Optional timezone-aware detector timestamp used to center the profile window.",
    )
    include_error_samples: bool = Field(
        default=True,
        description="Include at most 20 bounded Loki error samples from the profile window.",
    )


class AgentSpawnerRequest(BaseModel):
    name: str = Field(description="Short machine-readable name for the spawned sub-agent.")
    system_prompt: str = Field(description="System prompt that defines the spawned sub-agent's role and evidence-gathering objective.")
    user_prompt: str = Field(description="Task prompt to run through the spawned sub-agent.")
    tools: list[str] = Field(description="Exact registered tool names to expose to the spawned sub-agent. Use prometheus, loki, and the registered network.* names directly; do not invent method suffixes. Do not include agent_spawner.")
    max_rounds: int = Field(
        default=10,
        ge=5,
        le=20,
        description="Maximum LLM/tool rounds for the spawned sub-agent. Use 10 normally, 5 for simple focused checks, and a higher value up to 20 for complex multi-signal investigations.",
    )


class RemediatorWriteFileRequest(BaseModel):
    session_id: str = Field(description="Explicit remediation job/session UUID.")
    filename: str = Field(description="Filename to create inside the active remediation session folder, e.g. remediation.yml, inventory.ini, manifest.yaml, or rollback.yaml. Path separators are not allowed.")
    content: str = Field(description="Complete file content to write.")


class RemediatorRunAnsibleRequest(BaseModel):
    session_id: str = Field(description="Explicit remediation job/session UUID.")
    playbook_file: str = Field(default="remediation.yml", description="Basename of the playbook inside the session folder, usually remediation.yml. Do not include directories or the session UUID.")
    inventory_file: str | None = Field(default=None, description="Optional inventory basename inside the session folder. Create it with remediator.write_file first when needed.")
    check: bool = Field(default=True, description="Run ansible_runner.run in Ansible check mode when true. Set false for live execution after validation and automation guardrails pass.")
    extra_vars: dict[str, Any] | None = Field(default=None, description="Optional extra variables passed to ansible_runner.run.")


class ToolCallOutput(BaseModel):
    name: str = Field(description="Function name.")
    kwargs: dict[str, Any] = Field(default_factory=dict, description="Keyword arguments used in the function.")
    result: Any = Field(description="Output of the tool.")
# fmt: on


TOOL_SCHEMAS = {
    "kubectl": FlexibleKubectlRequest,
    "prometheus": FlexiblePrometheusRequest,
    "loki": FlexibleLokiRequest,
    "jaeger.list_services": JaegerListServicesRequest,
    "jaeger.retrieve_slow_traces": JaegerRetrieveSlowTracesRequest,
    "jaeger.investigate_trace": JaegerInvestigateTraceRequest,
    "jaeger.retrieve_bottleneck": JaegerRetrieveBottleneckRequest,
    "network.topology": NetworkTopologyRequest,
    "network.latency_matrix": NetworkLatencyMatrixRequest,
    "network.bandwidth": NetworkBandwidthRequest,
    "network.path": NetworkPathRequest,
    "network.dns": NetworkDnsRequest,
    "network.tcp_connect": NetworkTcpConnectRequest,
    "cluster.profile_baseline": ClusterProfileBaselineRequest,
    "agent_spawner": AgentSpawnerRequest,
    "remediator.write_file": RemediatorWriteFileRequest,
    "remediator.run_ansible": RemediatorRunAnsibleRequest,
}
