apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
# Capacity-weighted placement for:
# worker-node-1: 8 CPU / 32 GiB
# worker-node-2, worker-node-3, worker-node-6: 4 CPU / 16 GiB
# worker-node-4, worker-node-5: 2 CPU / 8 GiB
resources:
  - ../../base
  - hpa.yaml
patches:
  - path: node-selector-path.yaml
    target:
      kind: Deployment
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: adservice
    patch: &worker1 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-1]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cartservice
    patch: *worker1
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: checkoutservice
    patch: &worker2 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-2, worker-node-4]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: currencyservice
    patch: &worker3 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-3, worker-node-5]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: emailservice
    patch: &worker4 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-2, worker-node-4]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
    patch: |-
      - op: add
        path: /spec/replicas
        value: 6
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-1, worker-node-2, worker-node-6]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: paymentservice
    patch: &worker5 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-3, worker-node-5]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: productcatalogservice
    patch: *worker3
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: recommendationservice
    patch: *worker1
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis-cart
    patch: &worker6 |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: [worker-node-4, worker-node-6]
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: shippingservice
    patch: *worker6
