apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  namespace: sock-shop
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: session-db
          resources:
            requests: {cpu: 50m, memory: 128Mi}
            limits: {cpu: 300m, memory: 512Mi}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {sizeLimit: 512Mi}
