apiVersion: v1
kind: Secret
metadata:
  name: learning-agent-secrets
  namespace: agents
type: Opaque
stringData:
  AGENT_STORE_TOKEN: "++++++++"
  LEARNING_SUBMIT_TOKEN: "++++++++"
  CLIENT_URL: "++++++++"
  CLIENT_TOKEN: "++++++++"
  LANGFUSE_PUBLIC_KEY: "++++++++"
  LANGFUSE_SECRET_KEY: "++++++++"
  LANGFUSE_BASE_URL: "++++++++"
