apiVersion: v1
kind: Secret
metadata:
  name: evaluation-runner-ssh
  namespace: agents
type: Opaque
stringData:
  id_ed25519: "++++++++"
  known_hosts: "++++++++"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-runner-env
  namespace: agents
type: Opaque
stringData:
  POSTGRES_DSN: "++++++++"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-runner-s3
  namespace: agents
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "++++++++"
  AWS_SECRET_ACCESS_KEY: "++++++++"
  AWS_DEFAULT_REGION: "++++++++"
  S3_RESULTS_URI: "++++++++"
