apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-persistence-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-persistence
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-auth-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-auth
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-image-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-image
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-recommender-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-recommender
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  minReplicas: 6
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
